### ISSUE TITLE
What is the purpose of `test_data.csv`?

### ISSUE THREAD

**Issue by cccs-kevin** [ANSSI-FR/AnoMark#2]
Hi @ajunius-ANSSI et al,

I see that `train_data.csv` and `train_data.txt` are used in the tests, but I cannot seem to find where `test_data.csv` is being used? If it is not being used anywhere, can it be removed?

Thanks!

Kevin 🇨🇦

**Comment by ajunius-ANSSI** [comment]
Hello,

The only purpose of `test_data.csv` is to apply a sample model on, to be sure nothing breaks. We could have used it also in the tests but we did not, maybe we forgot !

Best regards
Alexandre 🇫🇷
