### ISSUE TITLE
Open-source datasets containing command lines?

### ISSUE THREAD

**Issue by cccs-kevin** [ANSSI-FR/AnoMark#9]
Hi @ajunius-ANSSI,

Are you aware of any open-source datasets consisting of benign command lines? We would like to release an open-source version of the AnoMark service that we use in [Assemblyline](https://cybercentrecanada.github.io/assemblyline4_docs/) but the model we use cannot be released to the public unfortunately due to the dataset it was trained on.

Kevin

**Comment by ajunius-ANSSI** [comment]
Hello @cccs-kevin,

We've already had this type of question but we've never released a model based on open-source dataset. The main reason is we want the users to clearly understand that the algorithm is system-specific. Therefore I have never searched extensively an open-source dataset you can train a model on, but I know some researchers are working on this kind of problematic.

Alexandre

**Comment by cccs-kevin** [comment]
Fair enough, thanks for the response!
